# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true
          NODE_ENV: production
      - name: Push to remote
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name "github-actions[bot]"	
          git config --global user.email "github-actions[bot]@users.noreply.github.com"	
          rm -f .gitignore	
          git checkout -b release
          git add --all
          git commit --quiet -m "Built from ${{ github.sha }}" || echo "No changes to commit"
          git push origin release -f
